[mypy]
strict = True
warn_unreachable = True
warn_unused_ignores = True
disallow_untyped_decorators = True

[mypy-yfinance.*]
ignore_missing_imports = True

[mypy-matplotlib.*]
ignore_missing_imports = True

[mypy-pythonjsonlogger.*]
ignore_missing_imports = True

[mypy-alpaca.*]
ignore_missing_imports = True
